In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
os.chdir(r'C:\Users\nanda\employee-attrition')

In [3]:
df_left = pd.read_csv('employee_who_left.csv')

In [4]:
df_left.shape

(3571, 10)

In [5]:
df_left.head()

Emp ID  satisfaction_level  last_evaluation  number_project  \
0       1                0.38             0.53               2   
1       2                0.80             0.86               5   
2       3                0.11             0.88               7   
3       4                0.72             0.87               5   
4       5                0.37             0.52               2   

   average_montly_hours  time_spend_company  Work_accident  \
0                   157                   3              0   
1                   262                   6              0   
2                   272                   4              0   
3                   223                   5              0   
4                   159                   3              0   

   promotion_last_5years   dept  salary  
0                      0  sales     low  
1                      0  sales  medium  
2                      0  sales  medium  
3                      0  sales     low  
4                      0  sales     low

In [6]:
df_left_copy = df_left.copy()

In [7]:
df_left_copy['target'] = 1

In [8]:
df_emp = pd.read_csv('existing_employee.csv')

In [9]:
df_emp.head()

Emp ID  satisfaction_level  last_evaluation  number_project  \
0    2001                0.58             0.74               4   
1    2002                0.82             0.67               2   
2    2003                0.45             0.69               5   
3    2004                0.78             0.82               5   
4    2005                0.49             0.60               3   

   average_montly_hours  time_spend_company  Work_accident  \
0                   215                   3              0   
1                   202                   3              0   
2                   193                   3              0   
3                   247                   3              0   
4                   214                   2              0   

   promotion_last_5years   dept salary  
0                      0  sales    low  
1                      0  sales    low  
2                      0  sales    low  
3                      0  sales    low  
4                      0  sales    low

In [10]:
df_emp.shape

(11428, 10)

In [11]:
df_emp_copy = df_emp.copy()

In [12]:
df_emp_copy['target'] = 0

In [13]:
# final_df.append(df_emp_copy, ignore_index=True)
final_df = pd.concat([df_left_copy,df_emp_copy])

In [14]:
final_df.shape

(14999, 11)

In [15]:
final_df.columns

Index(['Emp ID', 'satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident',
       'promotion_last_5years', 'dept', 'salary', 'target'],
      dtype='object')

In [16]:
final_df =final_df.drop('Emp ID',axis=1)

In [17]:
final_df.tail()

satisfaction_level  last_evaluation  number_project  \
11423                0.90             0.55               3   
11424                0.74             0.95               5   
11425                0.85             0.54               3   
11426                0.33             0.65               3   
11427                0.50             0.73               4   

       average_montly_hours  time_spend_company  Work_accident  \
11423                   259                  10              1   
11424                   266                  10              0   
11425                   185                  10              0   
11426                   172                  10              0   
11427                   180                   3              0   

       promotion_last_5years        dept salary  target  
11423                      1  management   high       0  
11424                      1  management   high       0  
11425                      1  management   high       0  
11426                      1   marketing   high       0  
11427                      0          IT    low       0

In [18]:
# shuffling dataframe

In [19]:
final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [20]:
final_df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.73             0.86               4                   133   
1                0.21             0.77               6                   215   
2                0.60             0.98               4                   195   
3                0.41             0.47               2                   154   
4                0.77             0.87               5                   257   

   time_spend_company  Work_accident  promotion_last_5years         dept  \
0                   3              0                      0    technical   
1                   4              0                      0        sales   
2                   3              0                      0      support   
3                   3              0                      0        sales   
4                   2              0                      0  product_mng   

   salary  target  
0    high       0  
1  medium       0  
2  medium       0  
3     low       1  
4  medium       0

In [21]:
final_df['dept'].value_counts()

sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: dept, dtype: int64

In [22]:
final_df['salary'].value_counts()

low       7316
medium    6446
high      1237
Name: salary, dtype: int64

In [23]:
# from sklearn.preprocessing import LabelEncoder
# # instantiate labelencoder object
# le = LabelEncoder()

# categorical_cols = ['salary','dept']

# # apply le on categorical feature columns
# final_df[categorical_cols] = final_df[categorical_cols].apply(lambda col: le.fit_transform(col))    
# from sklearn.preprocessing import OneHotEncoder
# ohe = OneHotEncoder()

# #One-hot-encode the categorical columns.
# #Unfortunately outputs an array instead of dataframe.
# array_hot_encoded = ohe.fit_transform(final_df[categorical_cols])

# #Convert it to df
# data_hot_encoded = pd.DataFrame(array_hot_encoded) #, index=final_df.index

# #Extract only the columns that didnt need to be encoded
# data_other_cols = final_df.drop(columns=categorical_cols)

# #Concatenate the two dataframes : 
# data_out = pd.concat([data_hot_encoded, data_other_cols], axis=1)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
final_df
final_df = pd.get_dummies(final_df, columns = ['salary','dept'])

In [26]:
final_df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.73             0.86               4                   133   
1                0.21             0.77               6                   215   
2                0.60             0.98               4                   195   
3                0.41             0.47               2                   154   
4                0.77             0.87               5                   257   

   time_spend_company  Work_accident  promotion_last_5years  target  \
0                   3              0                      0       0   
1                   4              0                      0       0   
2                   3              0                      0       0   
3                   3              0                      0       1   
4                   2              0                      0       0   

   salary_high  salary_low  ...  dept_IT  dept_RandD  dept_accounting  \
0            1           0  ...        0           0                0   
1            0           0  ...        0           0                0   
2            0           0  ...        0           0                0   
3            0           1  ...        0           0                0   
4            0           0  ...        0           0                0   

   dept_hr  dept_management  dept_marketing  dept_product_mng  dept_sales  \
0        0                0               0                 0           0   
1        0                0               0                 0           1   
2        0                0               0                 0           0   
3        0                0               0                 0           1   
4        0                0               0                 1           0   

   dept_support  dept_technical  
0             0               1  
1             0               0  
2             1               0  
3             0               0  
4             0               0  

[5 rows x 21 columns]

In [27]:
final_df.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
promotion_last_5years    0
target                   0
salary_high              0
salary_low               0
salary_medium            0
dept_IT                  0
dept_RandD               0
dept_accounting          0
dept_hr                  0
dept_management          0
dept_marketing           0
dept_product_mng         0
dept_sales               0
dept_support             0
dept_technical           0
dtype: int64

In [28]:
final_df.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident',
       'promotion_last_5years', 'target', 'salary_high', 'salary_low',
       'salary_medium', 'dept_IT', 'dept_RandD', 'dept_accounting', 'dept_hr',
       'dept_management', 'dept_marketing', 'dept_product_mng', 'dept_sales',
       'dept_support', 'dept_technical'],
      dtype='object')

In [29]:
X = final_df.drop(['target'], axis=1)
y = final_df['target']

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [31]:
print(f'X_train shape{X_train.shape}')
print(f'X_test shape{X_test.shape}')
print('*'*25)
print(f'y_train shape{y_train.shape}')
print(f'y_test shape{y_test.shape}')

X_train shape(10499, 20)
X_test shape(4500, 20)
*************************
y_train shape(10499,)
y_test shape(4500,)


# Baseline model(Decision Tree)

In [32]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model = model.fit(X_train, y_train)
 
y_pred = model.predict(X_test)
print(y_pred)

[1 1 0 ... 0 0 0]


In [33]:
from sklearn.metrics import confusion_matrix 

def get_metrics(true_values, pred_values):
    print('Confusion matrix \n')
    cm= confusion_matrix(true_values, pred_values) 
    print(cm)
    print('*'*30)
    print ("Accuracy : ",accuracy_score(true_values, pred_values)*100)
    print('*'*30)
    print("Report : \n",classification_report(true_values, pred_values))
    

In [34]:
from sklearn.metrics import accuracy_score, classification_report

get_metrics(y_test,y_pred)

Confusion matrix 

[[3396   55]
 [  35 1014]]
******************************
Accuracy :  98.0
******************************
Report : 
               precision    recall  f1-score   support

           0       0.99      0.98      0.99      3451
           1       0.95      0.97      0.96      1049

    accuracy                           0.98      4500
   macro avg       0.97      0.98      0.97      4500
weighted avg       0.98      0.98      0.98      4500



# RandomForest

In [35]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier()
rf_model = rf_model.fit(X_train, y_train)
 
rf_y_pred = rf_model.predict(X_test)
print(rf_y_pred)

[1 1 0 ... 0 0 0]


In [36]:
get_metrics(y_test,rf_y_pred)

Confusion matrix 

[[3441   10]
 [  33 1016]]
******************************
Accuracy :  99.04444444444445
******************************
Report : 
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      3451
           1       0.99      0.97      0.98      1049

    accuracy                           0.99      4500
   macro avg       0.99      0.98      0.99      4500
weighted avg       0.99      0.99      0.99      4500

